name: sqlite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  get: ^4.6.5
  path: ^1.8.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_native_splash: ^2.2.10
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png  # Asegúrate de que el archivo exista en esta ruta

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#D2B48C"  # Color de fondo (puedes cambiarlo a tu color preferido)
  image: assets/icon/icon.png  # Ruta al ícono (ajusta según tu ubicación del ícono)
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center
  # Ajuste de duración (requiere código adicional para asegurar un tiempo específico)


